### ISSUE TITLE
Why use RenderDoc to capture gpu frame for Vulkan failed?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#101]
When I use RenderDoc to capture gpu frame for debug on Vulkan , it always cause RenderDoc remote server disconnected. For example in the Textured3DCubeSession demo.

If i use opengl backend , the RenderDoc works fine.

if i use [The diligent engine](https://github.com/DiligentGraphics/DiligentEngine) demo for test vulkan demo, the RenderDoc works fine too.

**Comment by vinsentli** [comment]
I use RenderDoc on Windows to connect My Android phone.
My Windows RenderDoc version is V1.32

**Comment by corporateshark** [comment]
That sounds like it might be a RenderDoc issue.

@vinsentli Could you please check https://renderdoc.org/docs/how/how_android_capture.html.

**Comment by vinsentli** [comment]
After I open the vulkan VK_LAYER_KHRONOS_validation (https://developer.android.com/ndk/guides/graphics/validation-layer?hl=zh-cn#layers-local-storage)

RenderDoc capture frame successful.
