### ISSUE TITLE
The memory usage of the Vulkan is three times higher than the OpenGL ?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#108]
Is it normal for the memory usage of the Vulkan demo in the Textured3DCubeSession to be three times higher than the OpenGL demo?

The memory usage of Textured3DCubeSession On my Huawei Mate60 phone:
Vulkan, GL Memory : 334M
<img width="279" alt="image" src="https://github.com/facebook/igl/assets/7352338/fdef07dd-3d48-4964-97f9-90812f562442">

But the OpenGLES3.0 GL Memory only : 97M
<img width="249" alt="image" src="https://github.com/facebook/igl/assets/7352338/cb74c4ee-56b1-4353-ac85-4517825bcce3">

**Comment by corporateshark** [comment]
@vinsentli You can set the parameter `VulkanContextConfig::vmaPreferredLargeHeapBlockSize` to 16Mb to reduce the amount of memory preallocated for VMA pools. https://github.com/facebook/igl/commit/2a6324125773f02e65ebc9b5021713eb16435d43
