### ISSUE TITLE
Does DeviceFeatureLimits::BufferAlignment mean GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#109]
Does DeviceFeatureLimits::BufferAlignment mean GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT?

If it is , the BufferAlignment on iOS Simulator for metal, it  is 256 bytes. 
And On iOS Device, its is 16 bytes.

[https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator](https://developer.apple.com/documentation/metal/developing_metal_apps_that_run_in_simulator)
【When you set arguments for the render or compute command, align constant buffer offsets to 256 bytes.】

<img width="798" alt="image" src="https://github.com/facebook/igl/assets/7352338/c3ac89d3-0225-4216-8925-8152b305a4f8">

**Comment by corporateshark** [comment]
@vinsentli Thanks for pointing this out! I will take a closer look this week.
