### ISSUE TITLE
The input parameter requirements  of API [Framebuffer::copyBytesColorAttachment] are inconsistent on different backend !

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#120]
`void Framebuffer::copyBytesColorAttachment(ICommandQueue& /* unused */,
                                           size_t index,
                                           void* pixelBytes,
                                           const TextureRangeDesc& range,
                                           size_t bytesPerRow).`

When I want to copy part of the buffer from the whole ColorAttachment texture, the input parameter requirement are inconsistent on different backend.

First, the range TextureRangeDesc.y is different on OpenGL and Metal/Vulkan.
On OpenGL, TextureRangeDesc.y  Y-axis facing upwards.
On Metal/Vulkan, TextureRangeDesc.y  Y-axis facing downwards.

Second, the bytesPerRow is also different on OpenGL and Metal/Vulkan.
On OpenGL , the bytesPerRow must be the whole texture width multiply by bytesPerPixel.
On Metal/Vulkan, the bytesPerRow must be Zero.
I Cann't use the same bytesPerRow, or it will cause exception on different backend.

**Comment by francoiscoulombe** [comment]
hey @vinsentli that sounds pretty bad. I'll try to take a look in the next few weeks.
let us know if this is blocking you

**Comment by vinsentli** [comment]
@francoiscoulombe  I have made adaptations in my code, so I can continue working. However, I would like to ensure consistency when calling the API in the end.
