### ISSUE TITLE
Raytracing?

### ISSUE THREAD

**Issue by AntarticCoder** [facebook/igl#13]
Is raytracing within the scope of this project. Metal, DirectX and Vulkan all seem to have a way to do raytracing. I don't have experience with DirectX since I'm on a Mac, however I have seen the differences between Metal and Vulkan's raytracing API, and it seems that they could map well to each other. Thanks!

**Comment by rudybear** [comment]
Raytracing is definitely within the scope of this project, we just have no chance to work on this yet. The minor obstacle at this point to start implement this feature is the current API design. The most part of common functionality is implemented across all backend APIs with some exceptions. These exceptions are not handled super nicely at this moment (in most of the cases we have just non-implemented stubs) . RT is available only on Metal and Vulkan (and possible DX IGL port) and impossible to implement as is on any OpenGL flavors. That means we need to emphasize some sort of backend API features mechanism first to handle these exceptions more consistently. Not super big deal, but it obviously would takes some effort.

**Comment by AntarticCoder** [comment]
Thanks for the response, I'm intrested in contributing and this is a good answer.
