### ISSUE TITLE
[Vulkan] CommandBuffer::popDebugGroupLabel() Crash after CommandBuffer::waitUntilCompleted()

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#143]
If call CommandBuffer::popDebugGroupLabel() after CommandBuffer::waitUntilCompleted(), it will crash.

```
void CommandBuffer::popDebugGroupLabel() const {
  ivkCmdEndDebugUtilsLabel(&ctx_.vf_, wrapper_.cmdBuf_);
}
```

Because wrapper_.cmdBuf_  has been set to VK_NULL_HANDLE in VulkanImmediateCommands::purge().

The callstack is : 
CommandBuffer::waitUntilCompleted() --> VulkanImmediateCommands::wait()-->VulkanImmediateCommands::purge()

**Comment by corporateshark** [comment]
@vinsentli Why do you want to call `popDebugGroupLabel()` after a command buffer submission?

**Comment by vinsentli** [comment]
@corporateshark I just want to keep the gpu capture tree clear. 
And There is no negative effects on OpenGL or Metal when Call popDebugGroupLabel() after CommandBuffer::Submit().
Of course, it is not necessary.

**Comment by corporateshark** [comment]
@vinsentli I see. Can you do `popDebugGroupLabel()` before `Submit()`?

**Comment by vinsentli** [comment]
@corporateshark  Yes, I can call popDebugGroupLabel() before Submit()

**Comment by corporateshark** [comment]
@vinsentli Did it solve your issue?
