### ISSUE TITLE
Vulkan |  Switch between the foreground and background

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#150]
```c++
JNIEXPORT void JNICALL Java_com_facebook_igl_shell_SampleLib_surfaceDestroyed(JNIEnv* env,
                                                                              jobject /*obj*/,
                                                                              jobject surface) {
  // For Vulkan we deallocate the whole renderer and recreate it when surface is re-created.
  // This is done because we currently don't have an easy way to destroy the surface + swapchain
  // independent of the whole device.
  // This is not needed for GL
  if (activeBackendTypeID == BackendTypeID::Vulkan && renderers[activeBackendTypeID] != nullptr) {
    renderers[activeBackendTypeID]->onSurfaceDestroyed(
        surface ? ANativeWindow_fromSurface(env, surface) : nullptr);
    auto& renderer = renderers[activeBackendTypeID];
    renderer.reset();
    renderers[activeBackendTypeID] = nullptr;
  }
}
``` 

When I tried to switch between the foreground and background on Vulkan, I found that it is currently not possible. This is because every time the surface is destroyed, the entire render, including all data and textures, needs to be destroyed. This is unacceptable in a real app. Is it possible to only replace the surface while keeping the device available during the switch between foreground and background?

**Comment by vinsentli** [comment]
@corporateshark @rokuz 
Is this issue a problem with the sample code or is it due to the current API not supporting it yet?

**Comment by vinsentli** [comment]
@rokuz Thanks for your response. Do you have an approximate timeframe for this?

**Comment by vinsentli** [comment]
@corporateshark 
Please provide us with some support, as it is crucial for us.
Thanks!

**Comment by corporateshark** [comment]
@vinsentli As @rokuz mentioned, we do not have any defined timeframe for this. I'm really sorry about that!

**Comment by vinsentli** [comment]
I have resolved this issue : recreate swap chain when switch app from background to foreground

Old:

https://github.com/user-attachments/assets/84a90d3e-d59d-4ebe-8af6-acddd5d5dc3e

New:

https://github.com/user-attachments/assets/e242ad78-0130-4184-82f4-ef15b93f7cad

**Comment by vinsentli** [comment]
close
