### ISSUE TITLE
unused variable

### ISSUE THREAD

**Issue by maddin200** [facebook/igl#151]
File:
igl-main\shell\renderSessions\GPUStressSession.cpp line 373 + 545

Code:
 if (threadId != -1) {
    setCurrentThreadAffinityMask(1 << threadId);
  }
  const std::random_device rd; // <-- unused
  std::mt19937 gen(0);

**Comment by francoiscoulombe** [comment]
thank you, I just submitted something to remove those.

**Comment by francoiscoulombe** [comment]
issue should be fixed as soon as the repo syncs
