### ISSUE TITLE
where could I found the performance test result compared with Vulkan or OGL?

### ISSUE THREAD

**Issue by wenshengsheng2020** [facebook/igl#16]

**Comment by corporateshark** [comment]
It is possible to run our [Bistro demo app](https://github.com/facebook/igl/blob/main/samples/desktop/Tiny/Tiny_MeshLarge.cpp#L49) in both Vulkan and OpenGL modes and see the difference for yourself.

We do not have any other pre-made performance test results yet, sorry about that!
