### ISSUE TITLE
Which platforms does TinyMeshSession demo support?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#162]
I have tested it on Android and macOS (ARM-based chip：Apple M1 Pro), but it doesn't work on either of them.

**Comment by corporateshark** [comment]
@vinsentli It should be possible to run on Windows, Android (with Vulkan 1.3) and desktop macOS.

**Comment by vinsentli** [comment]
@corporateshark 
MacOS crash:

-[MTLDebugDevice newBufferWithBytes:length:options:]:670: failed assertion `Buffer Validation
options 0x2 conveys invalid cpuCacheMode of 0x2
'
<img width="1862" alt="image" src="https://github.com/user-attachments/assets/720bd807-31fb-473c-ba17-56d9a9754e4a">

**Comment by corporateshark** [comment]
It does not have proper Metal shaders yet. But it should run with Vulkan and MoltenVK.
