### ISSUE TITLE
sample Tiny_MeshLarge error.

### ISSUE THREAD

**Issue by yangyagami** [facebook/igl#17]
[IGL] Error in (igl::Result igl::opengl::RenderPipelineState::create(const igl::RenderPipelineDesc&)).
Sampler uniform (texSkyboxIrradiance) not found in shader.
[IGL] Error in (igl::Result igl::opengl::RenderPipelineState::create(const igl::RenderPipelineDesc&)).
Sampler uniform (texAlpha) not found in shader.
[IGL] Error in (igl::Result igl::opengl::RenderPipelineState::create(const igl::RenderPipelineDesc&)).
Sampler uniform (texDiffuse) not found in shader.
[IGL] Error in (igl::Result igl::opengl::RenderPipelineState::create(const igl::RenderPipelineDesc&)).
Sampler uniform (texAmbient) not found in shader.
[IGL] Error in (igl::Result igl::opengl::RenderPipelineState::create(const igl::RenderPipelineDesc&)).
Sampler uniform (texShadow) not found in shader.
[IGL] Error in (igl::Result igl::opengl::RenderPipelineState::create(const igl::RenderPipelineDesc&)).
uniform block (MeshMaterials) not found in shader.
[IGL] Error in (igl::Result igl::opengl::ShaderModule::create(const igl::ShaderModuleDesc&)).
failed to compile vertex shader:
0:1(1): error: syntax error, unexpected NEW_IDENTIFIER

**Comment by yangyagami** [comment]
Source
precision mediump float;attribute vec2 position; attribute vec2 texCoords; attribute vec4 color; uniform mat4 projectionMatrix; varying vec2 Frag_UV; varying vec4 Frag_Color; void main() { Frag_UV = texCoords; Frag_Color = color; gl_Position = projectionMatrix * vec4(position.xy, 0, 1); }[IGL] Assert failed in 'Ptr igl::opengl::{anonymous}::createResource(const Desc&, igl::Result*, Params&& ...) [with Ptr = std::shared_ptr<igl::opengl::ShaderModule>; Desc = igl::ShaderModuleDesc; Params = {igl::opengl::IContext&, const igl::ShaderModuleInfo&}]' (/home/jiale/Workspace/igl/src/igl/opengl/Device.cpp:68): 0:1(1): error: syntax error, unexpected NEW_IDENTIFIER

**Comment by corporateshark** [comment]
Thanks for the bug report!

Could you please tell us more about how to reproduce this issue?

**Comment by yangyagami** [comment]
> Thanks for the bug report!
> 
> Could you please tell us more about how to reproduce this issue?

When I start program It will reproduce the issue. I started it by opengl backend.

**Comment by yangyagami** [comment]
![image](https://github.com/facebook/igl/assets/45322657/e02d483c-1a53-461f-a75f-7415416be1c4)
My system is arch linux.

**Comment by corporateshark** [comment]
7d90f29e3542e5efa372ba18acdcd7359da4f375
