### ISSUE TITLE
【Metal】MTLBuffer was not properly released

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#179]
I noticed that even though igl::meta::Buffer is released after running the program for a while, MTLBuffer is not properly released, and the memory keeps increasing. For example, in the screenshot below, there are only 298 objects in igl::metal::Buffer, but CaptureMTLBuffer still has 3882 objects. 

   One solution I found is to call [MTLBuffer setPurgeableState:MTLPurgeableStateEmpty], which prevents the continuous memory growth even though the number of CaptureMTLBuffer objects doesn't decrease. 

My solution:
```c++
Buffer::~Buffer(){
  for (auto & buf : mtlBuffers_){
    [buf setPurgeableState:MTLPurgeableStateEmpty];
    buf = nil;
  }
  mtlBuffers_.clear();
}
``` 

However, [MTLBuffer setPurgeableState:MTLPurgeableStateEmpty] is typically used in non-ARC environments and theoretically should not be necessary in an ARC environment.

<img width="368" alt="image" src="https://github.com/user-attachments/assets/6de4aca1-1f71-4b0b-bc78-b5941ae794a2">

**Comment by tgoulart** [comment]
`Capture*` objects are associated with frame capture, which we do not control. Does it still happen if you disable "GPU Frame Capture" under the Scheme options?

**Comment by vinsentli** [comment]
@tgoulart  Disable "GPU Frame Capture" , it still happen.
