### ISSUE TITLE
Name igl or libigl ?

### ISSUE THREAD

**Issue by adammaj1** [facebook/igl#19]
What is the relation between [libigl](https://github.com/libigl/libigl) and [igl library](https://github.com/facebook/igl) ? 

      A library known as foo is expected to exist as the file libfoo.so or libfoo.a.

**Comment by EricGriffith** [comment]
There is no relation between IGL and libigl.

**Comment by adammaj1** [comment]
OK. Is these 2 similar names  confusing ? What do you think about putting some info about it ?

**Comment by zzilch** [comment]
Yeah, libigl is well-known geometry processing library for many years.
I truly appriate this new library. But I thinks these names must be confusing. 
Since both libraries are for graphics purpose, it is highly likely to use them together.
