### ISSUE TITLE
Is there a fallback for VK when VK_EXT_descriptor_indexing is missing?

### ISSUE THREAD

**Issue by sDeemm** [facebook/igl#20]
Hello, I'm targeting mobile devices where I want Vulkan to be the primary backend. The README states that `VK_EXT_descriptor_indexing` is required. It seems that this extension does not have a good coverage (<27%) on Android (source: https://vulkan.gpuinfo.org/). am I right to assume that VK will fail for those and therefore need to use a OpenGLES backend or there's alternative/fallback in the VK backend so it'll work but it's up to the user to not use descriptor indexing.

**Comment by corporateshark** [comment]
Hi!

There's no fallback for devices without [VK_EXT_descriptor_indexing](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_EXT_descriptor_indexing.html) and [VK_KHR_buffer_device_address](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VK_KHR_buffer_device_address.html) support. The current target platform for our Vulkan backend is Quest 2/3/Pro.
