### ISSUE TITLE
bootstrap.py does not put filepath in quotes when running scripts

### ISSUE THREAD

**Issue by RRKS101** [facebook/igl#22]
As the title says; 
I was in the process of running pre-build steps when it failed due to a directory being cut short ("D:/Programming/Libraries/C++ Libraries/igl" to "D:/Programming/Libraries/C++")
This occurred on the `bc7enc` part only (Im guessing it was the first third-party project that used python to configure it).
Using Ctrl+F, I found the call to the log function for running scripts, prom there I just threw a bunch of print statements for values on each line, giving me the state and line where the error occurred which was [this line](https://github.com/facebook/igl/blob/5176f9148f1237e10bd62333406bbf9d071a4fe6/third-party/bootstrap.py#L432C79-L432C79). 
By inserting escaped quotes on either side of the filename variable, this was fixed for me.

```python
# from
dieIfNonZero(executeCommand(TOOL_COMMAND_PYTHON + " " + filename, False));
# to
dieIfNonZero(executeCommand(TOOL_COMMAND_PYTHON + " \"" + filename + "\"", False));
```

**Comment by corporateshark** [comment]
Thank you for the bug report!

`escapifyPath(filename)` should do it.
