### ISSUE TITLE
Why is Geometry shader not supported?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#230]
Why do IGL and WebGPU not support Geometry shaders?

<img width="649" alt="Clipboard_Screenshot_1734315061" src="https://github.com/user-attachments/assets/d8960f12-82a4-4211-b20b-79a84fbabb90" />

Because Metal does not support Geometry shaders ?

**Comment by corporateshark** [comment]
IGL does not support geometry shaders mainly because it prioritizes compatibility with a wide range of mobile GPUs, where geometry shaders are not efficiently supported.
