### ISSUE TITLE
Cmake compilation definitions not propagating upwards

### ISSUE THREAD

**Issue by jwric** [facebook/igl#25]
I'm not sure about this, but shouldn't IGL's cmake compilation definitions such as `IGL_BACKEND_ENABLE_OPENGL`, `IGL_BACKEND_ENABLE_VULKAN`, etc. be set on the IGLLibrary target, such that projects that include IGL as a subdirectory can also use the macro definitions which are used in the Macros.h file

Something like this to add compile options to the target
```cmake
get_directory_property(IGL_DEFS COMPILE_DEFINITIONS )
target_compile_definitions(IGLLibrary INTERFACE ${IGL_DEFS})
```

**Comment by corporateshark** [comment]
A family of `IGL_BACKEND_ENABLE_...` macros is used not only with CMake but with other internal build systems.

What is the specific problem you are trying to solve?

**Comment by corporateshark** [comment]
Ah, I see. Can you use `IGL_WITH_OPENGL` etc from here?

https://github.com/facebook/igl/blob/main/CMakeLists.txt#L118

Replacing `add_definitions("-DIGL_BACKEND_ENABLE_OPENGL=1")` with this should solve the problem long-term:
```
target_compile_definitions(IGLLibrary PUBLIC "IGL_BACKEND_ENABLE_OPENGL=1")
```
Same with `IGL_CMAKE_BUILD`. It should be replaced with:
```
target_compile_definitions(IGLLibrary PUBLIC "IGL_CMAKE_BUILD=1")
```

**Comment by jwric** [comment]
Yes, it does solve the problem when you put those compile definitions on the target instead. I guess my question is, should IGL put these definitions on the IGLLibrary target?

Something like this at the end of the top level [CMakeLists.txt](https://github.com/facebook/igl/blob/main/CMakeLists.txt#L118) file would solve the problem for anyone using IGL as a submodule
```cmake
get_directory_property(IGL_DEFS COMPILE_DEFINITIONS)
target_compile_definitions(IGLLibrary PUBLIC ${IGL_DEFS})
```

**Comment by corporateshark** [comment]
>>should IGL put these definitions on the IGLLibrary target

Yes. Because `IGLLibrary` is the only target you should depend on in your apps when using IGL (other targets, such as `IGLVulkan`, are transitive and will be used automatically when available).

**Comment by jwric** [comment]
Ok good! And what about IGL's dependencies, were meant to be used from the outside. Things such as GLFW are cloned into IGL as internal dependencies, but these dependencies aren't all transitive. In the case of GLFW, it is only linked to IGLLibrary when `IGL_WITH_SAMPLES` is set. In the end I would have to link GLFW myself in my cmake project by retrieving GLFW through IGL's third-party directory, which feels weird. All `IGL_WITH_DEPS` does it that if it's ON, it clones all of the deps internally, and doesn't if its not, it doesn't link all of them.

**Comment by corporateshark** [comment]
GLFW is not used anywhere below the `IGLLibrary` target, so it should be pretty safe to link against your own copy.
