### ISSUE TITLE
WebGPU backend

### ISSUE THREAD

**Issue by birkskyum** [facebook/igl#37]
What are the plans for adding a WebGPU backend to IGL?

**Comment by corporateshark** [comment]
There're plans to add WebGPU as mentioned in the roadmap here https://github.com/facebook/igl/blob/main/ROADMAP.md.
However, there haven't been any specific deadlines announced for when this might occur. We will certainly provide assistance with pull requests that incorporate that functionality.

**Comment by birkskyum** [comment]
The roadmap says:

> **How you can help:**
> Assist with new API porting, such as DirectX, WebGPU, or any preferred platform of your choice.

Just to clarify, would the addition of a WebGPU backend that rely on Dawn be considered an assistance?

**Comment by corporateshark** [comment]
> would the addition of a WebGPU backend that rely on Dawn be considered an assistance?

It depends on what would be the exact nature of that dependency. Could you please elaborate a bit more about it?

**Comment by birkskyum** [comment]
Sure. The entire Dawn implementation is in many ways an alternative to IGL, also having a Metal and Vulkan backend, but I'm only talking about using WebGPU/WGSL as a web target, through emscripten/wasm, not as a native target.

Since the browsers will be bundling WebGPU implementations, I was mainly referring to using the webgpu.h from Dawn.

**Comment by corporateshark** [comment]
@birkskyum Dawn comes with a different license (MIT vs Apache License). It is not possible to bundle a file from Dawn and put into IGL. However, having a dependency in https://github.com/facebook/igl/tree/main/third-party is possible. Anyway, although there are no fundamental obstacles to doing so, we will have to review your code before it can be merged.
