### ISSUE TITLE
Do I need to write different shaders for different backends?

### ISSUE THREAD

**Issue by tuzihao** [facebook/igl#38]

**Comment by pixelperfect3** [comment]
Yes, please see sample shaders in the unit tests: src/igl/tests/data/ShaderData.h

**Comment by tuzihao** [comment]
> Yes, please see sample shaders in the unit tests: src/igl/tests/data/ShaderData.h

Thanks for your answer. It is a heavy work to write multiple-version shaders. Is 'glsl + spir-v + (glsl to metal)' a good solution to IGL? Do you have any good practice sugession?
