### ISSUE TITLE
Any documdentation on how to get started to use for something like Three.JS which wraps around WebGL?

### ISSUE THREAD

**Issue by qdrk** [facebook/igl#4]
Sorry, a newbie in this area, I looked around the repo but couldn't find any docs.

**Comment by rudybear** [comment]
We are planning to release a wasm integration example in the nearest future.

**Comment by sstarr-protacore** [comment]
> We are planning to release a wasm integration example in the nearest future.

If you're expecting anyone to actually use this, then you're going to need to do better than that.

**Comment by corporateshark** [comment]
Emscripten WebAssembly triangle added https://github.com/facebook/igl/pull/15
