### ISSUE TITLE
OpenXR + IGL sample

### ISSUE THREAD

**Issue by BattleAxeVR** [facebook/igl#41]
I'm interested in using IGL for standalone VR (Quest / Pico / HTC), but I'd like to first validate how well it runs in VR on Quest.

I was told that there would be an OpenXR sample forthcoming at some point, is that still the case?

**Comment by rudybear** [comment]
We have C++ code here (https://github.com/facebook/igl/tree/main/shell/openxr/mobile), it's just not wrapped to CMake at this moment

**Comment by BattleAxeVR** [comment]
I got the openxr shell sample to build and run on Windows using some hardcoded cmake scripts, and while it works, I have doubts this was tested / completed fully.

Here's what I did so far,  using Visual Studio + cmake, I got it to run on my Quest 3 but I had to use some hacks.

https://github.com/BattleAxeVR/igl/commit/e9daa347c9e3b15c83f3a443783c21822fa89c93

First off, I had to comment out the required extension XR_FB_SWAPCHAIN_UPDATE_STATE_EXTENSION_NAME, which isn't enumerated over Link on Quest 3. I suppose this is a standalone-only extension, but it's not there on the latest openxr_loader.lib and V60 firmware + oculus runtime. 

The code surrounding it is also very odd: who exactly is using openxr on macos? Is there even an openxr runtime / loader for Apple Vision Pro or other Mac devices? I thought Apple had no support for OpenXR.

![image](https://github.com/facebook/igl/assets/11604039/d845b990-2690-4e45-9a45-49b892e94603)

I mean, I get that Metal is a good feature, long-term, but there isn't even an Android build that actually runs on Quest here, forcing me to try and hack this myself and wasting time on things that obviously aren't fully baked. Is anyone else but me trying to use this library at all? Why would MacOS support be higher priority (I had to hack another file to use the Windows platform instead of Mac, as well) than Quest standalone or PC for Link? I don't understand this at all:

![image](https://github.com/facebook/igl/assets/11604039/08cff043-5336-4b69-bc72-529820bdee7e)


Lastly, I only see out of the left eye when I tried to use any of the provided RenderSessions. It's clear that none of this was actually tested on Quest, or the code wasn't pushed. There are so many questionable and weird things in this repo, it's hard to take this seriously.

**Comment by BattleAxeVR** [comment]
Ok, I disabled the single pass stereo which seems to depend on that required extension which is missing on Link, and now using Textured3DCubeSession I see the cube in both eyes. But they don't converge, the view/proj matrices aren't correct.

I don't have time / inclination to debug this code, please ping me if this ever gets finished, until then I will just use hello_xr as the basis for my generic openxr client instead.

**Comment by corporateshark** [comment]
@BattleAxeVR Here are some sketches to get OpenXR up and running on Windows https://github.com/facebook/igl/pull/56
It will not fix convergence etc, just let you compile and run sessions using OpenXR.

**Comment by BattleAxeVR** [comment]
That's definitely a good start in the right direction. I can fix the per eye view/projection matrices fairly easily, I think it should be straightforward, at which point I'll do a PR so others can benefit / save debugging time as well.

**Comment by BattleAxeVR** [comment]
I'll close this as soon as I get a chance to compile and test it on Android / Quest. I'll open up a different issue for the per eye convergence and a PR for that. It's probably a trivial issue.

**Comment by BattleAxeVR** [comment]
@corporateshark I guess it's not ready yet for Android, I need that to work before proceeding. I also need GL ES, not just Vulkan, and the OpenXR sessions seem to be only Vulkan-based. Still, one issue at a time :)

![image](https://github.com/facebook/igl/assets/11604039/164d0913-52be-4c97-a7ab-bcb6ba138455)

**Comment by BattleAxeVR** [comment]
Q) is useSinglePassStereo_  supposed to work on PC + Vulkan? It appears not to work at all. Maybe it's an OpenGL only feature? Or it's a standalone only feature I presume. Oh right, I remember now, it depends on some FB XR swap chain extension being available, which it isn't on PC over Link/AirLink yet (or probably ever).

Still, it's curious when I disable this flag, the views don't converge, and it's not clear to be what's, in fact, wrong with the code as-is.  It looks correct to me, and very similar to hello_xr. I guess I'll have to hardcode some values copied from the hello_xr sample and pass those in there to see if the bug is in the actual draw calls or vertex shaders.

The eye poses's X positions have the correct local half IPD offsets (-ve for left eye, +ve for right eye). I wonder if projection matrix (computed from the FOV values which are anti-symmetric horizontally), if that code used is GL-specific instead of Vulkan. If GL worked on PC I could test this quickly.  

I suppose a better thing to do here is for me to wait for Android OpenXR cmake to be fixed, then I can test the rest of the code using single pass stereo, which should hopefully work properly.

**Comment by BattleAxeVR** [comment]
@corporateshark Any chance you guys can take a look at this? There are only a handful of issues on this github repo but lots of activity every day, I would really appreciate if someone could take the time to make this run on Quest. I don't think that's too much to ask given that Quest is Facebook's own VR solution.

**Comment by corporateshark** [comment]
@BattleAxeVR We are working on it https://github.com/facebook/igl/commit/f40658947c0d9f07f3fc0cd2a68e8d9a0a887099 and we will get there.

**Comment by BattleAxeVR** [comment]
Any ETA? I'm strongly considering making an executive decision and abandoning my plans to use IGL entirely. I opened this issue 5 months ago...what's the hold up, exactly? I want to use this for my PC VR streaming software but this is taking too long.

**Comment by BattleAxeVR** [comment]
Nevermind...I'm done.
