### ISSUE TITLE
'VMA_STATIC_VULKAN_FUNCTIONS' previously declared on the command line (VulkanHelpers.c)

### ISSUE THREAD

**Issue by tksuoran** [facebook/igl#47]
This warning message produces spam, so it would be nice to have it fixed somehow, surrounding defines with #ifndef or something.

**Comment by corporateshark** [comment]
Thanks for reporting, I will make a quick fix for this.

**Comment by corporateshark** [comment]
c72368151e4e7593de5b06d4661f1fcf6c3b5225
