### ISSUE TITLE
Feature request: Enable resource debug labels

### ISSUE THREAD

**Issue by tksuoran** [facebook/igl#48]
- Please enable setting debug labels to resources such as buffers and textures. On Vulkan this could use `VK_EXT_debug_utils` extension.
- Please allow reading the debug label accessible on resources using C++ API as well.
- Primary purpose is to improve Renderdoc support. Thanks!

**Comment by corporateshark** [comment]
You can do that by assigning debug labels to the member fields `debugName` in `igl::BufferDesc`, `igl::TextureDesc`, etc.

**Comment by tksuoran** [comment]
Thanks, I somehow forgot that.

Is there a way to query back the debug label from a resource?

**Comment by corporateshark** [comment]
> Is there a way to query back the debug label from a resource?
Not with IGL. We design the API to reduce the number of getter methods to a minimum.
