### ISSUE TITLE
Feature request: TextureFormatProperties improvements

### ISSUE THREAD

**Issue by tksuoran** [facebook/igl#49]
Here are some additions I would like to see in `TextureFormatProperties`:
- `bool isIndexed()`
- `bool isInteger()`
- `bool hasColor()`
- `bool hasDepth()`
- `bool hasStencil()`

Thanks!

**Comment by corporateshark** [comment]
Everything except `isIndexed()` would be easy. I will check it.

**Comment by corporateshark** [comment]
5c6bdff44b0f172556d22240f267e36a70ce105c
