### ISSUE TITLE
BufferAPIHintBits questions

### ISSUE THREAD

**Issue by tksuoran** [facebook/igl#50]
- Why is `BufferAPIHintBits::Ring` buffer specific to Metal? Functionality similar to `Ring` could be implemented on top of `IBuffer` API, so I wonder, are there some benefits of having it directly in `IBuffer`? But why only Metal?
- Is `BufferAPIHintBits::Bone` used for anything? I did one super quick search in igl repo and I did not find any uses.

**Comment by tksuoran** [comment]
Looks like `igl::vulkan::Buffer::upload()` at least references Ring buffer. So I guess references to metal `BufferAPIHintBits` is outdated, and Ring can be used with other APIs as well?

**Comment by corporateshark** [comment]
Yes, IGL/Vulkan supports the `BufferAPIHintBits` flag. IGL/OpenGL does not support this flag and does not require it.

**Comment by tksuoran** [comment]
It would be great if the documentation comments would be updated:

```
  enum BufferAPIHintBits : uint8_t {
    Atomic = 1 << 0,
    UniformBlock = 1 << 1, // Enforces UBO for OpenGL
    Query = 1 << 2,
    Bone = 1 << 3,
    Ring = 1 << 4, // Metal: Ring buffers with memory for each swapchain image
    NoCopy = 1 << 5, // Metal: The buffer should re-use previously allocated memory.
  };
```

**Comment by corporateshark** [comment]
I would make a fix for this one. Many thanks for reporting.

**Comment by corporateshark** [comment]
4265f2511c181bcd51e9c28d5598f6aabc78361e
