### ISSUE TITLE
Compile Error : Definition of implicit copy constructor for 'vbool' is deprecated 

### ISSUE THREAD

**Issue by Zheap** [facebook/igl#53]
Platform: Mac & Xcode

After having fixed the issue #52,  I try to build "HelloWorldSession" on Mac with Xcode, some errors occurred.

`Documents/Code/igl/third-party/deps/src/ktx-software/lib/basisu/encoder/cppspmd_sse.h:453:10 Definition of implicit copy constructor for 'vbool' is deprecated because it has a user-provided copy assignment operator
`

![image](https://github.com/facebook/igl/assets/15099275/cbc27d5d-4191-4856-b66f-04e5ad96405e)

How to fix it ?

**Comment by mriegger** [comment]
Interesting, I've done a fresh install of IGL and it built and ran HelloWorld fine. 

Could you try navigating to your Xcode build settings and looking for "Treat Warnings as Errors" and check what its value is?

![Screenshot 2023-11-12 at 8 35 24 PM](https://github.com/facebook/igl/assets/24629059/74169921-b532-4749-acc5-2bd4fb83ed91)

Perhaps IGL needs to force that setting to be off in cmake.

**Comment by Zheap** [comment]
> Interesting, I've done a fresh install of IGL and it built and ran HelloWorld fine.
> 
> Could you try navigating to your Xcode build settings and looking for "Treat Warnings as Errors" and check what its value is?
> 
> ![Screenshot 2023-11-12 at 8 35 24 PM](https://user-images.githubusercontent.com/24629059/282364789-74169921-b532-4749-acc5-2bd4fb83ed91.png)
> 
> Perhaps IGL needs to force that setting to be off in cmake.

"Treat Warnings as Errors" is also set to "No" in my project.
![image](https://github.com/facebook/igl/assets/15099275/74e8ea78-e008-4e76-8cac-8cc8789adc8d)

And in order to avoid any other factors, I completely deleted the IGL directory, re-downloaded IGL, and executed the following commands in sequence

`python deploy_content.py`
`python deploy_deps.py`
`cd build`
`cmake -G Xcode .. -DIGL_WITH_VULKAN=OFF`

Then open Xcode, build HelloWorldSession without doing any other operations, but the above errors were still occurred.
Is it possible that I have some libraries installed locally that cause them to conflict?

**Comment by corporateshark** [comment]
@mriegger It looks like the problem is in `KTX-Software` and the version IGL uses has that warnings-as-errors feature enabled.

In the more recent version, they added an option to control it and it is disabled by default.
https://github.com/KhronosGroup/KTX-Software/blob/84ee59dd27232ff60ea6ee135f67d46fde5c766b/CMakeLists.txt#L237

The simplest solution would be to update `KTX-Software` used in IGL to the latest version.

**Comment by Zheap** [comment]
> @mriegger It looks like the problem is in `KTX-Software` and the version IGL uses has that warnings-as-errors feature enabled.
> 
> In the more recent version, they added an option to control it and it is disabled by default. https://github.com/KhronosGroup/KTX-Software/blob/84ee59dd27232ff60ea6ee135f67d46fde5c766b/CMakeLists.txt#L237
> 
> The simplest solution would be to update `KTX-Software` used in IGL to the latest version.

It works!
I have switched the ktx-software to the latest main branch, the HelloWorldSession run successfully.
Thank you very much~ @corporateshark

**Comment by corporateshark** [comment]
34e0a4c2e585a34847ca83ead28a49e6a049be73
