### ISSUE TITLE
Problem with SPIRV reflection produced by DXC compiler

### ISSUE THREAD

**Issue by geor-kasapidi** [facebook/igl#58]
Hi! I have a problem with spirv relfection in IGL on [this](https://github.com/facebook/igl/blob/00691f0fa37f292593ada58116e01c3cddd5f6f8/src/igl/vulkan/util/SpvReflection.cpp#L202) line. I have a bunch of RWStructuredBuffers in my shader, and DXC emits [spirv for them](https://github.com/microsoft/DirectXShaderCompiler/blob/f94fe829f7944c97ea2646fc7950ae4e367d7136/docs/SPIR-V.rst?plain=1#L965C8-L965C8) as uniform+uniformblock decoration. My current solution for this is very dumb:

```
    const bool isStorage = (id.storageClass == SpvStorageClassUniform ||
                            id.storageClass == SpvStorageClassUniformConstant) && id.dset == 2; // kBindPoint_BuffersStorage
    const bool isUniform = (id.storageClass == SpvStorageClassUniform ||
                           id.storageClass == SpvStorageClassUniformConstant) && id.dset == 1; // kBindPoint_BuffersUniform
```

and it looks like the real one should use check for SpvDecorationBufferBlock maybe?

**Comment by corporateshark** [comment]
Thanks! Could you please make a PR with your hotfix? Then I can quickly do some internal testing.

**Comment by geor-kasapidi** [comment]
yes, for sure! @corporateshark please check the [PR](https://github.com/facebook/igl/pull/59)

**Comment by corporateshark** [comment]
@geor-kasapidi I'm hitting this validation error on `Tiny_Mesh` with PR #59. Which means the descriptor sets have become broken. Could you follow up on that?

```
Validation layer:
 Validation Error: VUID-VkGraphicsPipelineCreateInfo-layout-07988
 Object 0: handle = B8A507000000007C, type = VK_OBJECT_TYPE_SHADER_MODULE;
 MessageID = 0000000000000000
 vkCreateGraphicsPipelines(): pCreateInfos[0].pStages[1] SPIR-V (VK_SHADER_STAGE_FRAGMENT_BIT) uses descriptor slot [Set 0 Binding 1] (type `VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER`) but was not declared in the pipeline layout.
The Vulkan spec states: If a resource variables is declared in a shader, a descriptor slot in layout must match the shader stage
(https://vulkan.lunarg.com/doc/view/1.3.268.0/windows/1.3-extensions/vkspec.html#VUID-VkGraphicsPipelineCreateInfo-layout-07988)
[IGL] Assert failed in 'unsigned int __cdecl `anonymous-namespace'::vulkanDebugCallback(enum VkDebugUtilsMessageSeverityFlagBitsEXT,unsigned int,const struct VkDebugUtilsMessengerCallbackDataEXT *,void *)' (C:\open\fbsource\xplat\graphics\igl\public\src\igl\vulkan\VulkanContext.cpp:112): false
```

**Comment by geor-kasapidi** [comment]
@corporateshark sorry, i think i will have some time in the next week to investigate this - just now, i will close this issue and my pr, and come back with a better solution.
