### ISSUE TITLE
IGLU submodule compiled with Emscripten (WASM)

### ISSUE THREAD

**Issue by kalwalt** [facebook/igl#65]
At the moment the **IGLU** submodule is not compiled to WebAssembly, but in theory it should be possible.  As i know, the underlying libraries, imgui ktx and stb can be compiled with Emscripten. The IGLU submodule is necessary for the Tiny_MeshLarge example, so it would be a nice have.
I will report here my progresses and if it make sense i will send a PR.

**Comment by kalwalt** [comment]
With commit https://github.com/kalwalt/igl/commit/5a3274e7a77706d646691c0a681ac20cde553987 i was able to build the IGLU lib with Emscripten (emsdk 3.1.26) and i have tested also the Tiny_MeshLarge example on Windows 11 and it worked fine, i have not a linux or Mac so i can not be sure if it will compile under other platforms... If i have time i will adapt the Tiny_MeshLarge example to WASM.

**Comment by corporateshark** [comment]
Thanks! Could you please make a PR with your fix? Then I can quickly do some internal testing.

**Comment by kalwalt** [comment]
> Thanks! Could you please make a PR with your fix? Then I can quickly do some internal testing.

Yes of course, in this case we can see the response from github actions.

**Comment by kalwalt** [comment]
I created new PR #66

**Comment by corporateshark** [comment]
@kalwalt Thank you for your contribution!

PR closed via https://github.com/facebook/igl/commit/dadbb2a9c53b93106d1ca1ac49e4e3f04660399e.

**Comment by kalwalt** [comment]
> @kalwalt Thank you for your contribution!
> 
> PR closed via [dadbb2a](https://github.com/facebook/igl/commit/dadbb2a9c53b93106d1ca1ac49e4e3f04660399e).

Thank you! I will send another PR when i have the Tiny_MeshLarge and maybe another simple example with IGLU for wasm...

**Comment by corporateshark** [comment]
Disabled https://github.com/facebook/igl/commit/c33ac911ee43f30fb4f3071bc7e2dd9ec27349e5

**Comment by kalwalt** [comment]
> Disabled [c33ac91](https://github.com/facebook/igl/commit/c33ac911ee43f30fb4f3071bc7e2dd9ec27349e5)

@corporateshark so sad for this... 🥲
