### ISSUE TITLE
github action for WASM compilation

### ISSUE THREAD

**Issue by kalwalt** [facebook/igl#67]
Looking at your github actions, i can't see one dedicated to WASM with Emscripten, would you interested to add it? i mean it would be useful to have at least a test if it fails the main build process.

**Comment by corporateshark** [comment]
@kalwalt Yes, absolutely!

**Comment by kalwalt** [comment]
@corporateshark with the latest commit the build script went succesfully fr Emscripten but not for other platforms. I think i have to change the conditional in the Build part.
I tested on my fork see [the reports](https://github.com/kalwalt/igl/actions/runs/7783287785)

**Comment by corporateshark** [comment]
Merged in f5c9f5d47f20956c8f714aada646ecc29b006390.
