### ISSUE TITLE
 Does IGL OpenGL backend not support "glDrawElementsInstanced"?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#81]

**Comment by corporateshark** [comment]
`glDrawElementsInstanced()` is not supported. The closest functionality is `RenderCommandEncoder::drawIndexedIndirect()`.

**Comment by vinsentli** [comment]
@corporateshark 
Why is glDrawElementsInstanced not supported? What are the reasons behind this decision?

**Comment by corporateshark** [comment]
> Why is glDrawElementsInstanced not supported? What are the reasons behind this decision?

No reasons besides limited capacity to work on this feature. However, we would greatly appreciate any contributions from the community. Please consider submitting a pull request. Your help would be welcomed and valued!
