### ISSUE TITLE
Why does not use UniformBlocks in your openGL demo ? Is it not support in openGL ?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#99]
<img width="679" alt="image" src="https://github.com/facebook/igl/assets/7352338/74c351a0-9fed-4102-a71a-6a6156a8d7a5">

**Comment by corporateshark** [comment]
Those demos can run on GLES2 which does not support uniform blocks.

Other demos, such as https://github.com/facebook/igl/tree/main/samples/desktop/Tiny, have higher minimal requirements and use more advanced features.
